services:
  postgres_db:
    image: postgres:16
    container_name: auth_db
    environment:
        POSTGRES_DB: ${DB_NAME:-auth_db}
        POSTGRES_USER: ${DB_USER:-postgres}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
        - "${DB_PORT:-5432}:5432"
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:9-alpine
    container_name: auth_flyway
    depends_on:
      postgres_db:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres_db:5432/${DB_NAME} -user=${DB_USER} -password=${DB_PASSWORD} -schemas=${DB_SCHEMA} -connectRetries=20 migrate
    volumes:
      - ./applications/app-service/src/main/resources/db/migration:/flyway/sql/migration