server:
  port: ${PORT:8080}
spring:
  application:
    name: auth
  devtools:
    add-properties: false
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5440}
    database: ${DB_NAME:autenticacion_db}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
logging:
  level:
    com:
      crediya: ${LOG_LEVEL:INFO}
jwt:
  secret: ${JWT_SECRET:defaultSecretKey}
  expiration: ${JWT_EXPIRATION:3600000}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: http://localhost:4200,http://localhost:8080
app:
  paths:
    user:
      createUser: /api/v1/users
      findUserByIdentification: /api/v1/users/identification/{identificationNumber}
    auth:
      login: /api/v1/login
      findMe: /api/v1/me
