server:
  port: ${PORT:8080}
spring:
  application:
    name: autenticacion
  devtools:
    add-properties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer
          client-id: myclientid
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5440}
    database: ${DB_NAME:autenticacion_db}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
logging:
  level:
    com:
      crediya: ${LOG_LEVEL:INFO}
jwt:
  json-exp-roles: /roles
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: http://localhost:4200,http://localhost:8080
